# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_dataset": "00_extract.ipynb",
         "save_to_csv": "00_extract.ipynb",
         "extract_dataset_threaded": "00_extract.ipynb",
         "clean_genre": "02_clean.ipynb",
         "extract_backdrop_img": "02_clean.ipynb",
         "extract_poster_img": "02_clean.ipynb",
         "drop_col": "02_clean.ipynb",
         "create_splits": "02_clean.ipynb"}

modules = ["extract.py",
           "clean.py"]

doc_url = "https://Benjamintdk.github.io/DSAI_proj/"

git_url = "https://github.com/Benjamintdk/DSAI_proj/tree/main/"

def custom_doc_links(name): return None
