# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_dataset": "01_extract.ipynb",
         "extract_dataset_threaded": "01_extract.ipynb",
         "create_splits": "01_extract.ipynb"}

modules = ["extract.py"]

doc_url = "https://Benjamintdk.github.io/DSAI_proj/"

git_url = "https://github.com/Benjamintdk/DSAI_proj/tree/main/"

def custom_doc_links(name): return None
