# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_dataset": "00_extract.ipynb",
         "save_to_csv": "00_extract.ipynb",
         "extract_dataset_threaded": "00_extract.ipynb",
         "clean_genre": "01_eda.ipynb",
         "freq_words": "01_eda.ipynb",
         "req_image": "02_clean.ipynb",
         "extract_images_threaded": "02_clean.ipynb",
         "split_datetime": "02_clean.ipynb",
         "drop_col": "02_clean.ipynb",
         "create_splits": "02_clean.ipynb",
         "MovieDataset": "03_dataset.ipynb",
         "Tokenize": "03_dataset.ipynb",
         "RandomResizeCrop": "03_dataset.ipynb",
         "ToTensor": "03_dataset.ipynb",
         "NormalizeStandardize": "03_dataset.ipynb",
         "Compose": "03_dataset.ipynb",
         "freeze_all_but_layer": "04_model.ipynb",
         "cnn_encoder": "04_model.ipynb",
         "text_encoder": "04_model.ipynb",
         "meta_encoder": "04_model.ipynb",
         "decoder": "04_model.ipynb"}

modules = ["extract.py",
           "eda.py",
           "clean.py",
           "dataset.py",
           "model.py"]

doc_url = "https://Benjamintdk.github.io/DSAI_proj/"

git_url = "https://github.com/Benjamintdk/DSAI_proj/tree/main/"

def custom_doc_links(name): return None
